# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='picture/')),
                ('name', models.CharField(max_length=60)),
                ('details', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.Category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
