# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20190825_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='location',
            new_name='place',
        ),
    ]
